-- global.lua
-- Author: cndy1860
-- Date: 2018-12-25
-- Descrip: 全局变/常量

------ERR CODE------
ERR_MAIN = "ERR_MAIN"  		--主函数错误
ERR_NORMAL = "ERR_NORMAL"
ERR_FILE = "ERR_FILE"
ERR_PARAM = "ERR_PARAM"
ERR_TIMEOUT = "ERR_TIMEOUT"
ERR_WARNING = "ERR_WARNING"
ERR_UNKOWN = "ERR_UNKOWN"
ERR_TASK_ABORT = "ERR_TASK_ABORT"



CURRENT_TASK = "TASK_NONE"
IS_BREAKING_TASK = false